### ISSUE TITLE
What are the criteria for a PDS to be listed in the repo's README?

### ISSUE THREAD

**Issue by kjarex** [myConsciousness/atproto-pds-search#4]
I'm just wondering, by which criteria a PDS is listed in the README?
I'm asking because I'm missing `schnitzel-mit-pommes.de` in the list, while [atscan.net](https://atscan.net) mentions it.

It's not that I need it to be listed, I'm more interested if this PDS might not deliver/ respond with some required data or misbehaves in any other way!?

Should it indeed misbehave/ lack any necessary information, I would be interested in the details.

Thanks!

**Comment by myConsciousness** [comment]
Hi @kjarex , I just noticed your issue here!

It's based on plc.directory, and these are targets.

https://github.com/myConsciousness/atproto-pds-search/blob/f9e89e1cc1d60daa5ae47ccfd3fe9dfd788f6c6f/lib/atproto_pds_crawler.dart#L9-L12

**Comment by kjarex** [comment]
Thanks.

Do you have any idea why `schnitzel-mit-pommes.de` isn't recognised?
It has dids on `plc.diretory`, for example [did:plc:4kg4ebnn6x3wxnexoxxtuidl](https://plc.directory/did:plc:4kg4ebnn6x3wxnexoxxtuidl).

Just again for clarification: my intention is not to get it on the list (as the pds is not really used currently anyway), but just to rule out any technical misbehaviour of the pds 😀The same reason why it gets skipped here, might as well create issues with federation later.

**Comment by fatihsever** [comment]
The crawler started indexing on July 29 according to [the GitHub Actions workflow](https://api.github.com/repos/myConsciousness/atproto-pds-search/actions/workflows/61674341) (see the `created_at` field).
However, your DID was registered to the directory on May 12 according to [the PLC API](https://plc.directory/did:plc:4kg4ebnn6x3wxnexoxxtuidl/log/audit) (see the `createdAt` field).

I think DIDs which were registered before the June 29 are not crawled. FYI @myConsciousness

**Comment by mary-ext** [comment]
I'm seeing a whole lot more PDS instances than what this repo seems to suggest
https://github.com/mary-ext/atproto-scraping

I don't think the scraper is actually working, like, at all. It doesn't even list the US West PDS that Bluesky has (`*.us-west.host.bsky.network`)

**Comment by mary-ext** [comment]
I checked the `data/index.json` file, it seems to have just stopped crawling entirely
![image](https://github.com/myConsciousness/atproto-pds-search/assets/148872143/19a277d4-46f1-4566-ab97-5d251eb80522)
